Plant Pal
HenrikeStahlhut/plant-pal pull request #1
Opened 2023-06-22 15:52 UTC by HenrikeStahlhut

2023-06-23 11:43 UTC, MarcMogdanz requested changes

2023-06-23 11:43 UTC, MarcMogdanz commented on src/components/Header/Header.tsx
> +  );
```suggestion
  return (
    <HeaderContainer>{children}</HeaderContainer>
  );
```

no need for using react fragments if you only return one child (only needed if you wanna return multiple top level children)

 Usually react fragments get rendered to a `<div>` in the output (and not stripped out!) so it's best to only use them if you need them to reduce the html elements used in the output

2023-06-23 11:43 UTC, MarcMogdanz commented on src/components/Headline/Headline.tsx
> +  );
Same here

2023-06-23 11:43 UTC, MarcMogdanz commented on src/components/Menu/Menu.tsx
> +export default function Navigation() {
File is called `Menu` which would make me assume this is rather the Menu which is _part of_ the navigation but not the navigation itself, so best to align file + component names 👌

2023-06-23 11:43 UTC, MarcMogdanz commented on src/components/MenuButton/MenuButton.tsx
> +type Props = {
```suggestion
type MenuButtonProps = {
```

2023-06-23 11:43 UTC, MarcMogdanz commented on src/pages/index.tsx
> +      <Link href={"/rooms/all"}> go to rooms</Link>
What I usually tend to do is have e.g. an object mapping all the navigation paths, because you usually will link to certain pages (e.g. the room overview) from different parts in your app, but then you'll have to updatethe `"/rooms/all"` string everywhere manually




```typescript
// routes.ts (top level in src)
export const ROUTES = {
  "ROOMS_OVERVIEW": "/rooms/all"
}
```

and then you can use

```suggestion
      <Link href={ROUTES.ROOMS_OVERVIEW}> go to rooms</Link>
```

2023-06-23 11:46 UTC, HenrikeStahlhut commented on src/components/Header/Header.tsx
> +  );
✅

2023-06-23 11:48 UTC, HenrikeStahlhut commented on src/components/Menu/Menu.tsx
> +export default function Navigation() {
✅

2023-06-23 11:48 UTC, HenrikeStahlhut commented on src/components/MenuButton/MenuButton.tsx
> +type Props = {
✅

2023-06-23 11:51 UTC, HenrikeStahlhut commented on src/pages/index.tsx
> +      <Link href={"/rooms/all"}> go to rooms</Link>
That's such a good idea, never thought about that. This will make my life SO much easier, because i always forget to update the path strings

2023-07-30 19:23 UTC, MarcMogdanz requested changes

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/BackButton/Backbutton.tsx
> +export default function Backbutton({ href }: BackbuttonProps) {
```suggestion
type BackButtonProps = {
  href: string;
};

export default function BackButton({ href }: BackButtonProps) {
```

+ also rename the file and fix imports of this component

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/Banner/ErrorBanner.tsx
> +export default function ErrorBanner({ children }: ErrorProps) {
```suggestion
type ErrorBannerProps = {
  children: React.ReactNode;
};

const StyledErrorBanner = styled.div`
  display: flex;
  align-items: center;
  background-color: #f3a2a2;

  margin: 20px;
  padding: 10px;
  border-radius: 15px;

  div {
    margin: 0px 10px;
  }
`;

export default function ErrorBanner({ children }: ErrorBannerProps) {
```

just to keep it aligned everywhere

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/Banner/LoadingBanner.tsx
> +}
```suggestion
type LoadingBannerProps = {
  children: React.ReactNode;
};

const StyledLoadingBanner = styled.div`
  display: flex;
  align-items: center;
  justify-content: center;
`;

export default function LoadingBanner({ children }: LoadingBannerProps) {
  return <StyledLoadingBanner>{children}</StyledLoading>;
}
```

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/DeleteButton/DeleteButton.tsx
> +}
You could potentially add a default case which throws/shows an error, it shouldn't be possible to have this error state but never say never (as you have two `if` blocks) here, e.g.:

```suggestion
  }
  
  throw new Error("Unexpected type for delete button");
}
```

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/AddRoomModal/AddRoomModal.tsx
> +  //TODO: <br> to margin
```suggestion
  // TODO: <br> to margin
```

You can also add a rule to eslint to remind you to space out comments, just update your `.eslintrc` config file to match the following:


```json
{
  "extends": "next/core-web-vitals",
  "rules": [
    "spaced-comment": "error"
  ]
}
```

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/Menu/Menu.tsx
> +  const closeMenu = () => setMenuOpen(false);
This is kind of an interesting edge case. In your `onClick` handlers you pass down _a new function_ which _calls_ the `closeMenu` function, so:

```typescript
onClick={() => closeMenu()}
```

equals to

```typescript
onClick={() => setMenuOpen(false)}
```

Usually you want to have a separate function to handle the logic for that but in this case it's pretty straight forward just closing the modal (no complex state manipulations e.g.) so I'd rather use two time the direct call instead of defining the separate function, improves the performance one step at a time as you don't need to save/handle a separate helper function (`closeMenu`)

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/MenuButton/MenuButton.tsx
> +      <div />
Placeholder? Would add a `// TODO` with some explanations to the component 👌

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/RoomTile/RoomTile.tsx
> +    <>
You can get rid of the fragment as you're only returning one node anyway

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/RoomsList/RoomsList.tsx
> +    <>
No need for the fragment

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/TodoContainer/TodoContainer.tsx
Is this file even being used?

2023-07-30 19:23 UTC, MarcMogdanz commented on src/lib/formatRoomType.ts
> +
```suggestion
     case RoomType.INVALID:
       return "Invalid room type";
```

can be commented in again as you added the `INVALID` type to your prisma schema

2023-07-30 19:23 UTC, MarcMogdanz commented on src/lib/typeguards/roomType.ts
> +// function isRoomType(value: any): boolean { --> function gibt boolean zurück, aber wenn die function true ist wird RoomType zurück gegeben (hence value is RoomType)
Needs an english translation

2023-07-30 19:23 UTC, MarcMogdanz commented on src/pages/plants/[id].tsx
> +    console.log("res", res.ok);
You can also add an rule for handling these kind of things (add the same place explained in another comment):

```json
"rules": {
  "no-console": "error"
}
```

2023-07-30 19:23 UTC, MarcMogdanz commented on src/pages/plants/[id].tsx
> +    setDeleteError((await res.json()).error ?? "Could not delete plant");
Just as a general thing, usually you'd try to _end up_ in your _ideal_ state. So for this case pushing the new page to the router/redirecting would be the ideal case and you'd then try to weed out all other/error cases

If you want to, you can flip the `if (!res.ok)` check and set the error in there + return and end up with just the router push

2023-07-30 19:23 UTC, MarcMogdanz commented on src/pages/rooms/[id].tsx
> +    setDeleteError((await res.json()).error ?? "Could not delete plant");
```suggestion
    if (res.ok) {
      router.push("/rooms");
      return;
    }
    
    setDeleteError((await res.json()).error ?? "Could not delete plant");
```

It works without but it may lead to unwanted behaviour as the rest of the code (e.g. setting the error message) will still be run and may show if the router push/redirect takes a bit of time

2023-07-30 19:23 UTC, MarcMogdanz commented on src/routes.ts
> +  HOME: "/",
```suggestion
  HOME: "/",
  ROOMS_OVERVIEW: "/rooms",
```

triggering my inner OCD

2023-07-30 19:23 UTC, MarcMogdanz commented on src/components/PlantList/PlantList.tsx
> +  }
You can drop the `else` as you're returning within the `if` anyway so just having the final `return` statement outside & below your `if` is enough

2023-07-30 20:02 UTC, HenrikeStahlhut commented on src/components/BackButton/Backbutton.tsx
> +export default function Backbutton({ href }: BackbuttonProps) {
✅

2023-07-30 20:03 UTC, HenrikeStahlhut commented on src/components/Banner/ErrorBanner.tsx
> +export default function ErrorBanner({ children }: ErrorProps) {
✅

2023-07-30 20:04 UTC, HenrikeStahlhut commented on src/components/Banner/LoadingBanner.tsx
> +}
✅

2023-07-30 20:12 UTC, HenrikeStahlhut commented on src/components/DeleteButton/DeleteButton.tsx
> +}
```suggestion
  } else {
    throw new Error("Unexpected type for delete button");
  }
```

Do i need the else or can i simply add the throw new Error(..) after the bracket?

2023-07-30 20:14 UTC, HenrikeStahlhut commented on src/components/AddRoomModal/AddRoomModal.tsx
> +  //TODO: <br> to margin
Perfect, that very helpful :)

2023-07-30 20:15 UTC, HenrikeStahlhut commented on src/components/AddRoomModal/AddRoomModal.tsx
> +  //TODO: <br> to margin
✅

2023-07-30 20:17 UTC, HenrikeStahlhut commented on src/components/Menu/Menu.tsx
> +  const closeMenu = () => setMenuOpen(false);
✅

2023-07-30 20:24 UTC, HenrikeStahlhut commented on src/components/MenuButton/MenuButton.tsx
> +      <div />
It's not a placeholder, but actually the three bars of the menu icon.
If you take a look at the `MenuButton.styled.tsx` you'll see how the divs are used for animations etc. 

```
export const StyledOpenMenuButton = styled.button<{ open: boolean }>`
  @media (max-width: 600px) {
    position: ${({ open }) => (open ? "absolute" : "relative")};
    margin: 20px 50px;
    padding: 0;
    z-index: 2;
    background: transparent;
    color: ${({ open }) => (open ? "var(--white)" : "var(--dark-green)")};

    div {
      position: relative;
      width: 2rem;
      height: 0.25rem;
      border-radius: 10px;
      margin-top: 0.4rem;
      background-color: ${({ open }) =>
        open ? "var(--white)" : "var(--dark-green)"};

      transition: all 0.3s linear;
      transform-origin: 1px;

      :first-child {
        transform: ${({ open }) => (open ? "rotate(45deg)" : "rotate(0)")};
      }
      :nth-child(2) {
        opacity: ${({ open }) => (open ? "0" : "1")};
        transform: ${({ open }) =>
          open ? "translateX(20px)" : "translateX(0)"};
      }
      :nth-child(3) {
        transform: ${({ open }) => (open ? "rotate(-45deg)" : "rotate(0)")};
      }
    }
  }
`;

```

But you're right, it looks kind of silly if you're not familiar with the code. I will add an explanation comment :)

2023-07-30 20:26 UTC, HenrikeStahlhut commented on src/components/RoomTile/RoomTile.tsx
> +    <>
✅

2023-07-30 20:26 UTC, HenrikeStahlhut commented on src/components/RoomsList/RoomsList.tsx
> +    <>
✅

2023-07-30 20:29 UTC, HenrikeStahlhut commented on src/components/TodoContainer/TodoContainer.tsx
Yes, it's the container which displays the todo's on the home page (`index.tsx`). Its also used on the todo detail pages `/todo/upcoming/index.tsx `and `/todo/today/index.ts`

2023-07-30 20:31 UTC, HenrikeStahlhut commented on src/lib/formatRoomType.ts
> +
✅

2023-07-30 21:09 UTC, HenrikeStahlhut commented on src/lib/typeguards/roomType.ts
> +// function isRoomType(value: any): boolean { --> function gibt boolean zurück, aber wenn die function true ist wird RoomType zurück gegeben (hence value is RoomType)
✅

2023-07-30 21:11 UTC, HenrikeStahlhut commented on src/pages/plants/[id].tsx
> +    console.log("res", res.ok);
✅

2023-07-31 12:55 UTC, HenrikeStahlhut commented on src/pages/plants/[id].tsx
> +    setDeleteError((await res.json()).error ?? "Could not delete plant");
Good to know

2023-07-31 12:55 UTC, HenrikeStahlhut commented on src/pages/plants/[id].tsx
> +    setDeleteError((await res.json()).error ?? "Could not delete plant");
✅

2023-07-31 12:57 UTC, HenrikeStahlhut commented on src/pages/rooms/[id].tsx
> +    setDeleteError((await res.json()).error ?? "Could not delete plant");
✅

2023-07-31 12:58 UTC, HenrikeStahlhut commented on src/routes.ts
> +  HOME: "/",
✅

2023-07-31 12:59 UTC, HenrikeStahlhut commented on src/components/PlantList/PlantList.tsx
> +  }
✅

2023-07-31 19:46 UTC, merged